export interface Country {
  name: string
  formalName: string
}

export const COUNTRIES: Country[] = [
	{ "name": "Afeganistão", "formalName": "República Islâmica do Afeganistão"},
	{ "name": "Albânia", "formalName": "República da Albânia"},
	{ "name": "Algéria", "formalName": "República Democrática Popular da Algéria"},
	{ "name": "Samoa Americana", "formalName": "Território de Samoa Americana"},
	{ "name": "Andorra", "formalName": "Principado Andorra"},
	{ "name": "Angola", "formalName": "República de Angola"},
	{ "name": "Anguilla", "formalName": "Anguilla"},
	{ "name": "Antártida", "formalName": "Antártida"},
	{ "name": "Antigua e Barbuda", "formalName": "Antigua e Barbuda"},
	{ "name": "Argentina", "formalName": "República Argentina"},
	{ "name": "Armênia", "formalName": "República da Armênia"},
	{ "name": "Aruba", "formalName": "Aruba"},
	{ "name": "Austrália", "formalName": "Comunidade da Austrália"},
	{ "name": "Áustria", "formalName": "República da Áustria"},
	{ "name": "Azerbaijão", "formalName": "República do Azerbaijão"},
	{ "name": "Bahamas", "formalName": "Comunidade de Bahamas"},
	{ "name": "Bahrein", "formalName": "Reino do Bahrein"},
	{ "name": "Bangladesh", "formalName": "República Popular de Bangladesh"},
	{ "name": "Barbados", "formalName": "Barbados"},
	{ "name": "Bielorrússia", "formalName": "República da Bielorrússia"},
	{ "name": "Bélgica", "formalName": "Reino da Bélgica"},
	{ "name": "Belize", "formalName": "Belize"},
	{ "name": "Benin", "formalName": "República do Benin"},
	{ "name": "Bermuda", "formalName": "Bermuda"},
	{ "name": "Butão", "formalName": "Reino do Butão"},
	{ "name": "Bolívia", "formalName": "Estado Plurinacional da Bolívia"},
	{ "name": "Bósnia e Herzegovina", "formalName": "Bósnia e Herzegovina"},
	{ "name": "Botswana", "formalName": "República da Botswana"},
	{ "name": "Ilha Bouvet", "formalName": "Ilha Bouvet"},
	{ "name": "Brasil", "formalName": "República Federativa do Brasil"},
	{ "name": "Território Britânico do Oceano Índico", "formalName": "Território Britânico do Oceano Índico"},
	{ "name": "Brunei", "formalName": "Estado do Brunei Darussalam"},
	{ "name": "Bulgária", "formalName": "República da Bulgária"},
	{ "name": "Burkina Faso", "formalName": "Burkina Faso"},
	{ "name": "Burundi", "formalName": "República do Burundi"},
	{ "name": "Camboja", "formalName": "Reino do Camboja"},
	{ "name": "Camarões", "formalName": "República de Camarões"},
	{ "name": "Canadá", "formalName": "Canadá"},
	{ "name": "Cabo Verde", "formalName": "República do Cabo Verde"},
	{ "name": "Ilhas Cayman", "formalName": "Ilhas Cayman"},
	{ "name": "República Centro-Africana", "formalName": "República Centro-Africana"},
	{ "name": "Chade", "formalName": "República do Chade"},
	{ "name": "Chile", "formalName": "República do Chile"},
	{ "name": "China", "formalName": "República Popular da China"},
	{ "name": "Ilha Christmas", "formalName": "Território da Ilha Christmas"},
	{ "name": "Ilhas Cocos (Keeling)", "formalName": "Território das Ilhas Cocos (Keeling)"},
	{ "name": "Colômbia", "formalName": "República da Colômbia"},
	{ "name": "Comores", "formalName": "União das Comores"},
	{ "name": "Congo", "formalName": "República do Congo"},
	{ "name": "Congo (DR)", "formalName": "República Democrática do Congo"},
	{ "name": "Ilhas Cook", "formalName": "Ilhas Cook"},
	{ "name": "Costa Rica", "formalName": "República da Costa Rica"},
	{ "name": "Costa do Marfim", "formalName": "República da Costa do Marfim"},
	{ "name": "Croácia", "formalName": "República da Croácia"},
	{ "name": "Cuba", "formalName": "República de Cuba"},
	{ "name": "Chipre", "formalName": "República do Chipre"},
	{ "name": "República Tcheca", "formalName": "República Tcheca"},
	{ "name": "Dinamarca", "formalName": "Reino da Dinamarca"},
	{ "name": "Djibuti", "formalName": "República do Djibuti"},
	{ "name": "Dominica", "formalName": "Comunidade da Dominica"},
	{ "name": "República Dominicana", "formalName": "República Dominicana"},
	{ "name": "Equador", "formalName": "República do Equador"},
	{ "name": "Egito", "formalName": "República Árabe do Egito"},
	{ "name": "El Salvador", "formalName": "República El Salvador"},
	{ "name": "Guiné Equatorial", "formalName": "República do Guiné Equatorial"},
	{ "name": "Eritreia", "formalName": "Estado da Eritreia"},
	{ "name": "Estônia", "formalName": "República da Estônia"},
	{ "name": "Etiópia", "formalName": "República Democrática Federal da Etiópia"},
	{ "name": "Ilhas Malvinas", "formalName": "Ilhas Malvinas"},
	{ "name": "Ilhas Faroe", "formalName": "Ilhas Faroe"},
	{ "name": "Fiji", "formalName": "República do Fiji"},
	{ "name": "Finlândia", "formalName": "República da Finlândia"},
	{ "name": "França", "formalName": "República Francesa"},
	{ "name": "Guiana Francesa", "formalName": "Guiana Francesa"},
	{ "name": "Polinésia Francesa", "formalName": "Polinésia Francesa"},
	{ "name": "Terras Austrais e Antárticas Francesas", "formalName": "Território das Terras Austrais e Antárticas Francesas"},
	{ "name": "Gabão", "formalName": "República Gabonesa"},
	{ "name": "Gâmbia", "formalName": "República da Gâmbia"},
	{ "name": "Geórgia", "formalName": "Geórgia"},
	{ "name": "Alemanha", "formalName": "República Federal da Alemanha"},
	{ "name": "Gana", "formalName": "Repúblia de Gana"},
	{ "name": "Gibraltar", "formalName": "Gibraltar"},
	{ "name": "Grécia", "formalName": "República Helênica"},
	{ "name": "Groelândia", "formalName": "Groelândia"},
	{ "name": "Granada", "formalName": "Granada"},
	{ "name": "Guadalupe", "formalName": "Guadalupe"},
	{ "name": "Guão", "formalName": "Território do Guão"},
	{ "name": "Guatemala", "formalName": "República da Guatemala"},
	{ "name": "Guiné", "formalName": "República do Guiné"},
	{ "name": "Guiné-Bissau", "formalName": "República da Guiné-Bissau"},
	{ "name": "Guiana", "formalName": "República Cooperativa da Guiana"},
	{ "name": "Haiti", "formalName": "República do Haiti"},
	{ "name": "Ilhas Heard e McDonald", "formalName": "Território das Ilhas Heard e McDonald"},
	{ "name": "Vaticano", "formalName": "Estado da Cidade do Vaticano"},
	{ "name": "Honduras", "formalName": "República de Honduras"},
	{ "name": "Hong Kong", "formalName": "Região Administrativa Especial de Hong Kong da República Popular da China"},
	{ "name": "Hungria", "formalName": "Hungria"},
	{ "name": "Islândia", "formalName": "Islândia"},
	{ "name": "Índia", "formalName": "República da Índia"},
	{ "name": "Indonésia", "formalName": "República da Indonésia"},
	{ "name": "Iran", "formalName": "República Islâmica do Iran"},
	{ "name": "Iraque", "formalName": "República do Iraque"},
	{ "name": "Irlanda", "formalName": "Irlanda"},
	{ "name": "Israel", "formalName": "Estado de Israel"},
	{ "name": "Itália", "formalName": "República Italiana"},
	{ "name": "Jamaica", "formalName": "Jamaica"},
	{ "name": "Japão", "formalName": "Japão"},
	{ "name": "Jordânia", "formalName": "Reino Hachemita da Jordânia"},
	{ "name": "Cazaquistão", "formalName": "República do Cazaquistão"},
	{ "name": "Quênia", "formalName": "República do Quênia"},
	{ "name": "Kiribati", "formalName": "República do Kiribati"},
	{ "name": "Coreia do Norte", "formalName": "República Democrática Popular da Coreia"},
	{ "name": "Coreia do Sul", "formalName": "República da Coreia"},
	{ "name": "Kuwait", "formalName": "Estado do Kuwait"},
	{ "name": "Quirguistão", "formalName": "República Quirguiz"},
	{ "name": "Laos", "formalName": "República Democrática Popular Lau"},
	{ "name": "Letônia", "formalName": "República da Letônia"},
	{ "name": "Líbano", "formalName": "República Libanesa"},
	{ "name": "Lesoto", "formalName": "Reino do Lesoto"},
	{ "name": "Libéria", "formalName": "República da Libéria"},
	{ "name": "Líbia", "formalName": "Líbia"},
	{ "name": "Liechtenstein", "formalName": "Principado de Liechtenstein"},
	{ "name": "Lituânia", "formalName": "República da Lituânia"},
	{ "name": "Luxemburgo", "formalName": "Grão-Ducado do Luxemburgo"},
	{ "name": "Macao", "formalName": "Macao"},
	{ "name": "Macedônia", "formalName": "República da Macedônia"},
	{ "name": "Madagascar", "formalName": "República de Madagascar"},
	{ "name": "Malawi", "formalName": "República de Malawi"},
	{ "name": "Malásia", "formalName": "Malásia"},
	{ "name": "Maldivas", "formalName": "Reública de Maldivas"},
	{ "name": "Mali", "formalName": "República do Mali"},
	{ "name": "Malta", "formalName": "República de Malta"},
	{ "name": "Ilhas Marshall", "formalName": "República das Ilhas Marshall"},
	{ "name": "Martinica", "formalName": "Martinica"},
	{ "name": "Mauritânia", "formalName": "República Islâmica da Mauritânia"},
	{ "name": "Maurício", "formalName": "República de Maurício"},
	{ "name": "Mayotte", "formalName": "Departamento de Mayotte"},
	{ "name": "México", "formalName": "Estados Unidos Mexicanos"},
	{ "name": "Micronésia", "formalName": "Estados Federados da Micronesia"},
	{ "name": "Moldova", "formalName": "República de Moldova"},
	{ "name": "Mônaco", "formalName": "Principado de Mônaco"},
	{ "name": "Mongólia", "formalName": "Mongólia"},
	{ "name": "Montserrat", "formalName": "Montserrat"},
	{ "name": "Marrocos", "formalName": "Reino de Marrocos"},
	{ "name": "Moçambique", "formalName": "República de Moçambique"},
	{ "name": "Birmânia", "formalName": "República da União de Myanmar"},
	{ "name": "Namíbia", "formalName": "República da Namíbia"},
	{ "name": "Nauru", "formalName": "República de Nauru"},
	{ "name": "Nepal", "formalName": "República Democrática Federativa do Nepal"},
	{ "name": "Holanda", "formalName": "Holanda"},
	{ "name": "Antilhas Holandesas", "formalName": "Antilhas Holandesas"},
	{ "name": "Nova Caledônia", "formalName": "Nova Caledônia"},
	{ "name": "Nova Zelândia", "formalName": "Nova Zelândia"},
	{ "name": "Nicarágua", "formalName": "República da Nicarágua"},
	{ "name": "Niger", "formalName": "República do Niger"},
	{ "name": "Nigéria", "formalName": "República Federativa da Nigéria"},
	{ "name": "Niue", "formalName": "Niue"},
	{ "name": "Ilha Norfolk", "formalName": "Território da Ilha Norfolk"},
	{ "name": "Ilhas Marianas do Norte", "formalName": "Comunidade das Ilhas Marianas do Norte"},
	{ "name": "Noruega", "formalName": "Reino da Noruega"},
	{ "name": "Omã", "formalName": "Sultanato de Omã"},
	{ "name": "País de Gales", "formalName": "País de Gales"},
	{ "name": "Paquistão", "formalName": "República Islâmica do Paquistão"},
	{ "name": "Palau", "formalName": "República de Palau"},
	{ "name": "Palestina", "formalName": "Estado da Palestina"},
	{ "name": "Panamá", "formalName": "República do Panamá"},
	{ "name": "Papua-Nova Guiné", "formalName": "Estado Independente da Papua-Nova Guiné"},
	{ "name": "Paraguai", "formalName": "República do Paraguai"},
	{ "name": "Peru", "formalName": "República do Peru"},
	{ "name": "Filipinas", "formalName": "República das Filipinas"},
	{ "name": "Ilhas Picárnia", "formalName": "Ilhas Picárnia"},
	{ "name": "Polônia", "formalName": "República da Polônia"},
	{ "name": "Portugal", "formalName": "República Portuguesa"},
	{ "name": "Porto Rico", "formalName": "Comunidade do Porto Rico"},
	{ "name": "Catar", "formalName": "Estado do Catar"},
	{ "name": "Reunião", "formalName": "Polônia"},
	{ "name": "Romênia", "formalName": "Romênia"},
	{ "name": "Rússia", "formalName": "Federação Russa"},
	{ "name": "Ruanda", "formalName": "República da Ruanda"},
	{ "name": "Santa Helena", "formalName": "Saint Helena"},
	{ "name": "São Cristóvão", "formalName": "São Cristóvão"},
	{ "name": "Santa Lúcia", "formalName": "Santa Lúcia"},
	{ "name": "São Pedro e Miquelon", "formalName": "Coletividade Territorial de São Pedro e Miquelon"},
	{ "name": "São Vicente e Granadinas", "formalName": "São Vicente e Granadinas"},
	{ "name": "Samoa", "formalName": "Estado Independente de Samoa"},
	{ "name": "São Marino", "formalName": "República de São Marino"},
	{ "name": "Sao Tomé e Príncipe", "formalName": "República Democrática de Sao Tomé e Príncipe"},
	{ "name": "Arábia Saudita", "formalName": "Reino da Arábia Saudita"},
	{ "name": "Senegal", "formalName": "República do Senegal"},
	{ "name": "Sérvia e Montenegro", "formalName": "União Estatal de Sérvia e Montenegro"},
	{ "name": "Seicheles", "formalName": "República das Seicheles"},
	{ "name": "República da Serra Leoa", "formalName": "República da Serra Leoa"},
	{ "name": "Singapura", "formalName": "República da Singapura"},
	{ "name": "Eslováquia", "formalName": "República Eslovaca"},
	{ "name": "Eslovênia", "formalName": "República da Eslovênia"},
	{ "name": "Ilhas Salomão", "formalName": "Ilhas Salomão"},
	{ "name": "Somália", "formalName": "República da Somália"},
	{ "name": "África do Sul", "formalName": "República da África do Sul"},
	{ "name": "Ilhas Geórgia do Sul e Sandwich do Sul", "formalName": "Ilhas Geórgia do Sul e Sandwich do Sul"},
	{ "name": "Espanha", "formalName": "Reino da Espanha"},
	{ "name": "Sri Lanka", "formalName": "República Democrática Socialista do Sri Lanka"},
	{ "name": "Sudão", "formalName": "República do Sudão"},
	{ "name": "Suriname", "formalName": "República do Suriname"},
	{ "name": "Esvalbarde", "formalName": "Esvalbarde"},
	{ "name": "Suazilândia", "formalName": "Reino da Suazilândia"},
	{ "name": "Suécia", "formalName": "Reino da Suécia"},
	{ "name": "Suiça", "formalName": "Confederação Suiça"},
	{ "name": "Síria", "formalName": "República Árabe Síria"},
	{ "name": "Taiwan", "formalName": "Taiwan"},
	{ "name": "Tajiquistão", "formalName": "República do Tajiquistão"},
	{ "name": "Tanzânia", "formalName": "República Unida da Tanzânia"},
	{ "name": "Tailândia", "formalName": "Reino da Tailândia"},
	{ "name": "Timor-Leste", "formalName": "República Democrática de Timor-Leste"},
	{ "name": "Togo", "formalName": "República Togolesa"},
	{ "name": "Toquelau", "formalName": "Toquelau"},
	{ "name": "Tonga", "formalName": "Reino de Tonga"},
	{ "name": "Trinidad e Tobago", "formalName": "República da Trinidad e Tobago"},
	{ "name": "Tunísia", "formalName": "República da Tunísia"},
	{ "name": "Turquia", "formalName": "República da Turquia"},
	{ "name": "Turcomenistão", "formalName": "Turcomenistão"},
	{ "name": "Ilhas Turks e Caicos", "formalName": "Ilhas Turks e Caicos"},
	{ "name": "Tuvalu", "formalName": "Tuvalu"},
	{ "name": "Uganda", "formalName": "República de Uganda"},
	{ "name": "Ucrânia", "formalName": "Ucrânia"},
	{ "name": "Emirados Árabes", "formalName": "Emirados Árabes Unidos"},
	{ "name": "Reino Unido", "formalName": "Reino Unido da Grã-Bretanha e Irlanda do Norte"},
	{ "name": "Estados Unidos", "formalName": "Estados Unidos da América"},
	{ "name": "Ilhas Menores Distantes dos Estados Unidos", "formalName": "Ilhas Menores Distantes dos Estados Unidos"},
	{ "name": "Uruguai", "formalName": "República Oriental do Uruguai"},
	{ "name": "Uzbequistão", "formalName": "República do Uzbequistão"},
	{ "name": "Vanuatu", "formalName": "República de Vanuatu"},
	{ "name": "Venezuela", "formalName": "República Bolivariana da Venezuela"},
	{ "name": "Vietnam", "formalName": "República Socialista do Vietnam"},
	{ "name": "Ilhas Virgens Inglesas", "formalName": "Ilhas Virgens"},
	{ "name": "Ilhas Virgens (USA)", "formalName": "Ilhas Virgens dos Estados Unidos"},
	{ "name": "Wallis e Futuna", "formalName": "Wallis e Futuna"},
	{ "name": "Saara Ocidental", "formalName": "Saara Ocidental"},
	{ "name": "Iêmen", "formalName": "República do Iêmen"},
	{ "name": "Zâmbia", "formalName": "República do Zâmbia"},
	{ "name": "Zimbábue", "formalName": "República do Zimbábue"}
]
